# Generated by Django 4.2.3 on 2023-07-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('teamlead', 'teamlead'), ('employee', 'employee'), ('manager', 'manager')], max_length=30),
        ),
    ]
