# Generated by Django 4.2.3 on 2023-07-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_comment_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
