# Generated by Django 4.2.3 on 2023-07-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_parent_alter_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
