# Generated by Django 4.2.3 on 2023-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('completed', 'completed'), ('pending', 'pending'), ('inprogress', 'inprogress')], default='pending', max_length=10),
        ),
    ]
